#环境选择
spring:
  profiles:
    active: dev

#使用单配置文件多文档模式
---
#开发环境
server:
  port: 8080

spring:
  config:
    activate:
      on-profile:

  messages:
    basename: i18n.login
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&&characterEncoding=utf-8&&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

    #durid数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计的拦截的filter，stat：监控统计、log4j：日志记录、wall：防御sql注入
    #如果运行时报错 类找不到异常：log4j
    #就导入log4j依赖
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# 配置mybatis框架
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhong.pojo

---
#上线环境
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&&characterEncoding=utf-8&&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

    #durid数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true