spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&&characterEncoding=utf-8&&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# springboot整合mybatis就是接管了mybatis的核心配置文件
mybatis:
  # 我们需要在这里配置好mybatis的别名映射
  type-aliases-package: com.zhong.pojo
  # 配置接口实现xml文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
